### ISSUE TITLE
Owner Register functionality 

### ISSUE THREAD

**Issue by smithc02** [awayfromhome/awayfromhome#51]
When navigating to the signup option, then clicking the owner register option and click back to register, the following error occurs.

![Screen Shot 2019-03-24 at 11 55 43 AM](https://user-images.githubusercontent.com/45781303/54882807-cc520b80-4e2b-11e9-9a14-430cc1d4d876.png)

**Comment by dylanlee082** [comment]
Issue fixed with pull request #52, added a error handling that informs the user when a required field is not filled out, or when they have a incorrect username/password.
